apiVersion: v1
kind: Namespace
metadata:
  name: uday-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: uday-app
  namespace: uday-app
  labels:
    app: uday-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uday-app
  template:
    metadata:
      labels:
        app: uday-app
    spec:
      containers:
      - name: uday-app
        image: udaytc/add-uday-service:4eab094
        ports:
        - containerPort: 5000
