apiVersion: v1
kind: Service
metadata:
  name: uday-app-service
  namespace: uday-app
spec:
  selector:
    app: uday-app
  ports:
    - name: http
      port: 80           # Porta que o Istio vai usar para acessar
      targetPort: 5000   # Porta real no container
  type: ClusterIP