apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: uday-app-vs
  namespace: uday-app
spec:
  hosts:
  - uday-app.uday.com.br 
  gateways:
  - uday-app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: uday-app
        port:
          number: 5000