apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXMtYmFja3N0YWdl
  POSTGRES_PORT: NTQzMg==  # "5432" codificado em base64
  AUTH_GITHUB_CLIENT_ID: T3YyM2xpQmxEVUJhZElRUkFUOGw=
  AUTH_GITHUB_CLIENT_SECRET: Y2UyNGY3ZGUzZjg2YTIwMWU2YjllY2U3YTg3OTQxNzRkZjE2M2EwYg==

